### ISSUE TITLE
大佬您好，能否整合一个本科生和研究生的课表？

### ISSUE THREAD

**Issue by Meteors27** [determ1ne/grsical#3]

**Comment by cxz66666** [comment]
请参考 github.com/cxz66666/ugrsical

**Comment by cxz66666** [comment]
ping @determ1ne  and can you update Readme about this repo for ugrs students?

**Comment by determ1ne** [comment]
> ping @determ1ne and can you update Readme about this repo for ugrs students?

已更新 README ，参见 https://github.com/determ1ne/grsical/commit/c7770d83cd5fbb8beba0fb7b57f0c4ea757589bb
